// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Local Prisma Postgres exposes a separate shadow DB port (see `prisma dev ls`).
    // Required for `prisma migrate dev`. Not needed once you point at a hosted DB
    // where Prisma can create its own shadow database.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
